ami_id            = "ami-0a606d8395a538502"
instance_type     = "t2.micro"
availability_zone = "us-east-2a"
name              = "Prod_Instance"
env               = "Prod"
region            = "us-east-2"