ami_id            = "ami-0beaa649c482330f7"
instance_type     = "t2.micro"
availability_zone = "us-east-2a"
name              = "Prod_Instance"
env               = "Prod"
region            = "us-east-2"